INSERT INTO Local (uf, municipio)
VALUES
    ('PA', 'Abaetetuba'),
    ('SP', 'Adamantina'),
    ('PE', 'Afogados da Ingazeira'),
    ('SP', 'Agudos'),
    ('MG', 'Aimorés'),
    ('BA', 'Alagoinhas'),
    ('ES', 'Alegre'),
    ('MG', 'Alfenas'),
    ('MG', 'Almenara'),
    ('MT', 'Alta Floresta'),
    ('PA', 'Altamira'),
    ('MT', 'Alto Boa Vista'),
    ('CE', 'Alto Santo'),
    ('RS', 'Alvorada'),
    ('MG', 'Além Paraíba'),
    ('BA', 'Amargosa'),
    ('SP', 'Americana'),
    ('SP', 'Amparo'),
    ('PR', 'Ampére'),
    ('PA', 'Ananindeua'),
    ('SP', 'Andradina'),
    ('GO', 'Anicuns'),
    ('GO', 'Anápolis'),
    ('GO', 'Aparecida de Goiânia'),
    ('PR', 'Apucarana'),
    ('SE', 'Aracaju'),
    ('CE', 'Aracati'),
    ('ES', 'Aracruz'),
    ('GO', 'Araguapaz'),
    ('MG', 'Araguari'),
    ('TO', 'Araguatins'),
    ('TO', 'Araguaína'),
    ('AL', 'Arapiraca'),
    ('PR', 'Arapongas'),
    ('PR', 'Arapoti'),
    ('MT', 'Araputanga'),
    ('SC', 'Araranguá'),
    ('SP', 'Araraquara'),
    ('SP', 'Araras'),
    ('PE', 'Araripina'),
    ('RJ', 'Araruama'),
    ('PR', 'Araucária'),
    ('MG', 'Araxá'),
    ('SP', 'Araçatuba'),
    ('MG', 'Araçuaí'),
    ('PE', 'Arcoverde'),
    ('RO', 'Ariquemes'),
    ('SP', 'Arujá'),
    ('PR', 'Assis Chateaubriand'),
    ('SP', 'Assis'),
    ('SP', 'Atibaia'),
    ('TO', 'Augustinópolis'),
    ('SP', 'Avaré'),
    ('MA', 'Açailândia'),
    ('RN', 'Açu'),
    ('MA', 'Bacabal'),
    ('MA', 'Bacabeira'),
    ('MG', 'Baependi'),
    ('RS', 'Bagé'),
    ('SC', 'Balneário Camboriú'),
    ('MA', 'Balsas'),
    ('PR', 'Bandeirantes'),
    ('MG', 'Barbacena'),
    ('PA', 'Barcarena'),
    ('SP', 'Barra Bonita'),
    ('RJ', 'Barra Mansa'),
    ('MA', 'Barra do Corda'),
    ('MT', 'Barra do Garças'),
    ('PR', 'Barracão'),
    ('BA', 'Barreiras'),
    ('SP', 'Barretos'),
    ('SP', 'Barueri'),
    ('SP', 'Batatais'),
    ('CE', 'Baturité'),
    ('SP', 'Bauru'),
    ('SP', 'Bebedouro'),
    ('RJ', 'Belford Roxo'),
    ('MG', 'Belo Horizonte'),
    ('PE', 'Belo Jardim'),
    ('PE', 'Belém de São Francisco'),
    ('PA', 'Belém'),
    ('PA', 'Benevides'),
    ('RS', 'Bento Gonçalves'),
    ('SP', 'Bertioga'),
    ('MG', 'Bertópolis'),
    ('MG', 'Betim'),
    ('PE', 'Bezerros'),
    ('SP', 'Birigui'),
    ('SC', 'Blumenau'),
    ('MG', 'Boa Esperança'),
    ('RR', 'Boa Vista'),
    ('SP', 'Boituva'),
    ('MG', 'Bom Despacho'),
    ('BA', 'Bom Jesus da Lapa'),
    ('RJ', 'Bom Jesus do Itabapoana'),
    ('SP', 'Botucatu'),
    ('SP', 'Bragança Paulista'),
    ('PA', 'Bragança'),
    ('DF', 'Brasília'),
    ('PA', 'Breves'),
    ('MG', 'Brumadinho'),
    ('BA', 'Brumado'),
    ('SC', 'Brusque'),
    ('MA', 'Buriticupu'),
    ('MS', 'Caarapó'),
    ('PB', 'Cabedelo'),
    ('RJ', 'Cabo Frio'),
    ('PE', 'Cabo de Santo Agostinho'),
    ('SP', 'Cachoeira Paulista'),
    ('BA', 'Cachoeira'),
    ('RS', 'Cachoeirinha'),
    ('ES', 'Cachoeiro de Itapemirim'),
    ('AL', 'Cacimbinhas'),
    ('RO', 'Cacoal'),
    ('RN', 'Caicó'),
    ('SP', 'Caieiras'),
    ('PB', 'Cajazeiras'),
    ('GO', 'Caldas Novas'),
    ('RS', 'Camaquã'),
    ('BA', 'Camaçari'),
    ('MG', 'Cambuquira'),
    ('PR', 'Cambé'),
    ('CE', 'Camocim'),
    ('PR', 'Campina Grande do Sul'),
    ('PB', 'Campina Grande'),
    ('SP', 'Campinas'),
    ('MG', 'Campo Belo'),
    ('MS', 'Campo Grande'),
    ('PR', 'Campo Largo'),
    ('SP', 'Campo Limpo Paulista'),
    ('PI', 'Campo Maior'),
    ('PR', 'Campo Mourão'),
    ('MT', 'Campo Novo do Parecis'),
    ('MT', 'Campo Verde'),
    ('MG', 'Campos Gerais'),
    ('RJ', 'Campos dos Goytacazes'),
    ('RS', 'Canela'),
    ('SE', 'Canindé de São Francisco'),
    ('CE', 'Canindé'),
    ('RS', 'Canoas'),
    ('SC', 'Canoinhas'),
    ('PI', 'Canto do Buriti'),
    ('PA', 'Capanema'),
    ('PR', 'Capanema'),
    ('MG', 'Capelinha'),
    ('BA', 'Capim Grosso'),
    ('PR', 'Capitão Leônidas Marques'),
    ('SC', 'Capivari de Baixo'),
    ('SP', 'Capivari'),
    ('SP', 'Capão Bonito'),
    ('SP', 'Caraguatatuba'),
    ('MG', 'Carangola'),
    ('SP', 'Carapicuíba'),
    ('MG', 'Caratinga'),
    ('ES', 'Cariacica'),
    ('PE', 'Carpina'),
    ('PE', 'Caruaru'),
    ('SP', 'Casa Branca'),
    ('BA', 'Casa Nova'),
    ('CE', 'Cascavel'),
    ('PR', 'Cascavel'),
    ('MS', 'Cassilândia'),
    ('PA', 'Castanhal'),
    ('ES', 'Castelo'),
    ('MG', 'Cataguases'),
    ('GO', 'Catalão'),
    ('SP', 'Catanduva'),
    ('SC', 'Catanduvas'),
    ('CE', 'Caucaia'),
    ('RS', 'Caxias do Sul'),
    ('MA', 'Caxias'),
    ('SC', 'Caçador'),
    ('SP', 'Caçapava'),
    ('GO', 'Caçu'),
    ('SP', 'Cerquilho'),
    ('MA', 'Chapadinha'),
    ('SC', 'Chapecó'),
    ('PR', 'Cianorte'),
    ('GO', 'Cidade Ocidental'),
    ('PR', 'Clevelândia'),
    ('AM', 'Coari'),
    ('MA', 'Codó'),
    ('ES', 'Colatina'),
    ('TO', 'Colinas do Tocantins'),
    ('PR', 'Colombo'),
    ('MT', 'Colíder'),
    ('BA', 'Conceição do Coité'),
    ('PB', 'Conceição'),
    ('SP', 'Conchas'),
    ('PA', 'Concórdia do Pará'),
    ('SC', 'Concórdia'),
    ('MG', 'Conselheiro Lafaiete'),
    ('MG', 'Contagem'),
    ('PR', 'Cornélio Procópio'),
    ('MA', 'Coroatá'),
    ('MG', 'Coromandel'),
    ('MG', 'Coronel Fabriciano'),
    ('BA', 'Coronel João Sá'),
    ('PI', 'Corrente'),
    ('MS', 'Corumbá'),
    ('MS', 'Costa Rica'),
    ('SP', 'Cotia'),
    ('CE', 'Crateús'),
    ('CE', 'Crato'),
    ('SC', 'Criciúma'),
    ('GO', 'Cristalina'),
    ('CE', 'Croatá'),
    ('RS', 'Cruz Alta'),
    ('BA', 'Cruz das Almas'),
    ('PR', 'Cruzeiro do Oeste'),
    ('AC', 'Cruzeiro do Sul'),
    ('SP', 'Cruzeiro'),
    ('MT', 'Cuiabá'),
    ('PR', 'Curitiba'),
    ('RN', 'Currais Novos'),
    ('MG', 'Curvelo'),
    ('MT', 'Cáceres'),
    ('SP', 'Diadema'),
    ('MG', 'Diamantina'),
    ('MT', 'Diamantino'),
    ('BA', 'Dias d´Ávila'),
    ('MG', 'Divinópolis'),
    ('PR', 'Dois Vizinhos'),
    ('MS', 'Dourados'),
    ('SP', 'Dracena'),
    ('RJ', 'Duque de Caxias'),
    ('PI', 'Elesbão Veloso'),
    ('SP', 'Embu'),
    ('RS', 'Erechim'),
    ('PE', 'Escada'),
    ('MG', 'Espinosa'),
    ('SP', 'Espírito Santo do Pinhal'),
    ('RS', 'Estrela'),
    ('BA', 'Euclides da Cunha'),
    ('BA', 'Eunápolis'),
    ('CE', 'Eusébio'),
    ('MG', 'Extrema'),
    ('RS', 'Farroupilha'),
    ('BA', 'Feira de Santana'),
    ('SP', 'Fernandópolis'),
    ('SP', 'Ferraz de Vasconcelos'),
    ('PE', 'Floresta'),
    ('PI', 'Floriano'),
    ('SC', 'Florianópolis'),
    ('MG', 'Formiga'),
    ('GO', 'Formosa'),
    ('CE', 'Fortaleza'),
    ('PR', 'Foz do Iguaçu'),
    ('SP', 'Franca'),
    ('PR', 'Francisco Beltrão'),
    ('SP', 'Francisco Morato'),
    ('SP', 'Franco da Rocha'),
    ('RS', 'Frederico Westphalen'),
    ('MS', 'Fátima do Sul'),
    ('PE', 'Garanhuns'),
    ('RS', 'Garibaldi'),
    ('SP', 'Garça'),
    ('RS', 'Getúlio Vargas'),
    ('PE', 'Goiana'),
    ('GO', 'Goianésia'),
    ('GO', 'Goiatuba'),
    ('PR', 'Goioerê'),
    ('GO', 'Goiânia'),
    ('MG', 'Governador Valadares'),
    ('RS', 'Gravataí'),
    ('CE', 'Guaiúba'),
    ('BA', 'Guanambi'),
    ('MG', 'Guanhães'),
    ('PB', 'Guarabira'),
    ('SC', 'Guaramirim'),
    ('MT', 'Guarantã do Norte'),
    ('ES', 'Guarapari'),
    ('PR', 'Guarapuava'),
    ('SP', 'Guaratinguetá'),
    ('PR', 'Guaratuba'),
    ('TO', 'Guaraí'),
    ('SP', 'Guarujá'),
    ('SP', 'Guarulhos'),
    ('MG', 'Guaxupé'),
    ('ES', 'Guaçuí'),
    ('SP', 'Guaíra'),
    ('TO', 'Gurupi'),
    ('SP', 'Holambra'),
    ('CE', 'Horizonte'),
    ('RS', 'Horizontina'),
    ('SP', 'Hortolândia'),
    ('PR', 'Ibaiti'),
    ('BA', 'Ibicaraí'),
    ('SP', 'Ibitinga'),
    ('CE', 'Icó'),
    ('PA', 'Igarapé-Miri'),
    ('PE', 'Igarassu'),
    ('RS', 'Igrejinha'),
    ('MG', 'Iguatama'),
    ('CE', 'Iguatu'),
    ('RS', 'Ijuí'),
    ('SP', 'Ilha Solteira'),
    ('BA', 'Ilhéus'),
    ('MA', 'Imperatriz'),
    ('SC', 'Indaial'),
    ('SP', 'Indaiatuba'),
    ('GO', 'Indiara'),
    ('GO', 'Inhumas'),
    ('MG', 'Ipatinga'),
    ('SP', 'Ipaussu'),
    ('BA', 'Ipiaú'),
    ('BA', 'Ipirá'),
    ('PE', 'Ipojuca'),
    ('GO', 'Iporá'),
    ('PR', 'Iporã'),
    ('CE', 'Ipu'),
    ('BA', 'Irará'),
    ('PR', 'Irati'),
    ('BA', 'Irecê'),
    ('BA', 'Itaberaba'),
    ('GO', 'Itaberaí'),
    ('MG', 'Itabira'),
    ('MG', 'Itabirito'),
    ('RJ', 'Itaboraí'),
    ('BA', 'Itabuna'),
    ('AM', 'Itacoatiara'),
    ('RJ', 'Itaguaí'),
    ('PA', 'Itaituba'),
    ('SC', 'Itajaí'),
    ('MG', 'Itajubá'),
    ('BA', 'Itamaraju'),
    ('SP', 'Itanhaém'),
    ('SP', 'Itapecerica da Serra'),
    ('SC', 'Itapema'),
    ('RJ', 'Itaperuna'),
    ('SP', 'Itapetininga'),
    ('SP', 'Itapeva'),
    ('SP', 'Itapevi'),
    ('CE', 'Itapipoca'),
    ('SP', 'Itapira'),
    ('SC', 'Itapiranga'),
    ('GO', 'Itapuranga'),
    ('SP', 'Itaquaquecetuba'),
    ('SP', 'Itararé'),
    ('SP', 'Itatiba'),
    ('MG', 'Itaúna'),
    ('MA', 'Itinga do Maranhão'),
    ('SP', 'Itu'),
    ('MG', 'Ituiutaba'),
    ('GO', 'Itumbiara'),
    ('MG', 'Iturama'),
    ('SP', 'Ituverava'),
    ('SP', 'Itápolis'),
    ('PR', 'Ivaiporã'),
    ('PR', 'Ivatuba'),
    ('RS', 'Ivoti'),
    ('ES', 'Iúna'),
    ('PE', 'Jaboatão dos Guararapes'),
    ('SP', 'Jaboticabal'),
    ('PR', 'Jacarezinho'),
    ('SP', 'Jacareí'),
    ('MT', 'Jaciara'),
    ('BA', 'Jacobina'),
    ('PR', 'Jaguariaíva'),
    ('SP', 'Jaguariúna'),
    ('SP', 'Jales'),
    ('MG', 'Janaúba'),
    ('PR', 'Jandaia do Sul'),
    ('MG', 'Januária'),
    ('SC', 'Jaraguá do Sul'),
    ('RO', 'Jaru'),
    ('GO', 'Jataí'),
    ('SP', 'Jaú'),
    ('BA', 'Jequié'),
    ('RO', 'Ji-Paraná'),
    ('SC', 'Joaçaba'),
    ('SC', 'Joinville'),
    ('PE', 'João Alfredo'),
    ('MG', 'João Monlevade'),
    ('PB', 'João Pessoa'),
    ('MG', 'João Pinheiro'),
    ('MT', 'Juara'),
    ('MG', 'Juatuba'),
    ('CE', 'Juazeiro do Norte'),
    ('BA', 'Juazeiro'),
    ('MG', 'Juiz de Fora'),
    ('SP', 'Jundiaí'),
    ('SP', 'Junqueirópolis'),
    ('GO', 'Jussara'),
    ('MT', 'Juína'),
    ('SE', 'Lagarto'),
    ('SC', 'Lages'),
    ('MA', 'Lago da Pedra'),
    ('RS', 'Lajeado'),
    ('PR', 'Lapa'),
    ('BA', 'Lauro de Freitas'),
    ('MG', 'Lavras'),
    ('SP', 'Leme'),
    ('SP', 'Lençóis Paulista'),
    ('MG', 'Leopoldina'),
    ('SP', 'Limeira'),
    ('CE', 'Limoeiro do Norte'),
    ('PE', 'Limoeiro'),
    ('ES', 'Linhares'),
    ('SP', 'Lins'),
    ('PR', 'Londrina'),
    ('SP', 'Lorena'),
    ('MT', 'Lucas do Rio Verde'),
    ('SP', 'Lupércio'),
    ('MG', 'Luz'),
    ('GO', 'Luziânia'),
    ('BA', 'Luís Eduardo Magalhães'),
    ('AP', 'Macapá'),
    ('RJ', 'Macaé'),
    ('AL', 'Maceió'),
    ('MG', 'Machado'),
    ('SC', 'Mafra'),
    ('SP', 'Mairiporã'),
    ('AM', 'Manacapuru'),
    ('AM', 'Manaus'),
    ('PR', 'Mandaguari'),
    ('MG', 'Manhuaçu'),
    ('MG', 'Mantena'),
    ('PA', 'Marabá'),
    ('CE', 'Maracanaú'),
    ('RS', 'Marau'),
    ('PR', 'Marechal Cândido Rondon'),
    ('MG', 'Mariana'),
    ('RJ', 'Maricá'),
    ('PR', 'Maringá'),
    ('SP', 'Martinópolis'),
    ('SP', 'Marília'),
    ('MG', 'Matipó'),
    ('MG', 'Mato Verde'),
    ('MT', 'Matupá'),
    ('SP', 'Matão'),
    ('SP', 'Mauá'),
    ('PR', 'Medianeira'),
    ('RJ', 'Miguel Pereira'),
    ('CE', 'Milhã'),
    ('GO', 'Mineiros'),
    ('SP', 'Mirassol'),
    ('SP', 'Mococa'),
    ('SP', 'Mogi Guaçu'),
    ('SP', 'Mogi das Cruzes'),
    ('SP', 'Moji Mirim'),
    ('SP', 'Monte Aprazível'),
    ('MG', 'Monte Carmelo'),
    ('BA', 'Monte Santo'),
    ('MG', 'Montes Claros'),
    ('RN', 'Mossoró'),
    ('MS', 'Mundo Novo'),
    ('MG', 'Muriaé'),
    ('RN', 'Natal'),
    ('MG', 'Natalândia'),
    ('SC', 'Navegantes'),
    ('MS', 'Naviraí'),
    ('PE', 'Nazaré da Mata'),
    ('RJ', 'Niterói'),
    ('SE', 'Nossa Senhora do Socorro'),
    ('MS', 'Nova Andradina'),
    ('RJ', 'Nova Iguaçu'),
    ('MG', 'Nova Lima'),
    ('MT', 'Nova Mutum'),
    ('SP', 'Nova Odessa'),
    ('RS', 'Nova Petrópolis'),
    ('MG', 'Nova Porteirinha'),
    ('MG', 'Nova Serrana'),
    ('ES', 'Nova Venécia'),
    ('GO', 'Novo Gama'),
    ('RS', 'Novo Hamburgo'),
    ('SP', 'Novo Horizonte'),
    ('PA', 'Novo Progresso'),
    ('PE', 'Olinda'),
    ('MG', 'Oliveira'),
    ('SP', 'Olímpia'),
    ('SC', 'Orleans'),
    ('SP', 'Osasco'),
    ('SP', 'Osvaldo Cruz'),
    ('RS', 'Osório'),
    ('SP', 'Ourinhos'),
    ('MG', 'Ouro Fino'),
    ('RO', 'Ouro Preto do Oeste'),
    ('MG', 'Ouro Preto'),
    ('CE', 'Pacajus'),
    ('GO', 'Padre Bernardo'),
    ('SC', 'Palhoça'),
    ('PE', 'Palmares'),
    ('TO', 'Palmas'),
    ('AL', 'Palmeira dos Índios'),
    ('GO', 'Palmeiras de Goiás'),
    ('SC', 'Palmitos'),
    ('PR', 'Palotina'),
    ('RJ', 'Paracambi'),
    ('MG', 'Paracatu'),
    ('PA', 'Paragominas'),
    ('SP', 'Paraguaçu Paulista'),
    ('CE', 'Parambu'),
    ('PR', 'Paranaguá'),
    ('PR', 'Paranavaí'),
    ('MS', 'Paranaíba'),
    ('PA', 'Parauapebas'),
    ('PR', 'Paraíso do Norte'),
    ('TO', 'Paraíso do Tocantins'),
    ('AM', 'Parintins'),
    ('BA', 'Paripiranga'),
    ('RN', 'Parnamirim'),
    ('MA', 'Parnarama'),
    ('PI', 'Parnaíba'),
    ('MG', 'Pará de Minas'),
    ('RS', 'Passo Fundo'),
    ('MG', 'Passos'),
    ('PR', 'Pato Branco'),
    ('MG', 'Patos de Minas'),
    ('PB', 'Patos'),
    ('MG', 'Patrocínio'),
    ('RN', 'Pau dos Ferros'),
    ('PE', 'Paulista'),
    ('BA', 'Paulo Afonso'),
    ('SP', 'Paulínia'),
    ('MA', 'Paço do Lumiar'),
    ('SP', 'Pederneiras'),
    ('MA', 'Pedreiras'),
    ('MG', 'Pedro Leopoldo'),
    ('RS', 'Pelotas'),
    ('AL', 'Penedo'),
    ('SP', 'Penápolis'),
    ('SP', 'Pereira Barreto'),
    ('PE', 'Petrolina'),
    ('RJ', 'Petrópolis'),
    ('PI', 'Picos'),
    ('RO', 'Pimenta Bueno'),
    ('SP', 'Pindamonhangaba'),
    ('PR', 'Pinhais'),
    ('SC', 'Pinhalzinho'),
    ('MA', 'Pinheiro'),
    ('GO', 'Piracanjuba'),
    ('SP', 'Piracicaba'),
    ('SP', 'Piraju'),
    ('MG', 'Pirapora'),
    ('SP', 'Pirassununga'),
    ('SP', 'Piratininga'),
    ('GO', 'Pires do Rio'),
    ('PI', 'Piripiri'),
    ('PR', 'Pitanga'),
    ('TO', 'Pium'),
    ('SP', 'Pompéia'),
    ('PR', 'Ponta Grossa'),
    ('MS', 'Ponta Porã'),
    ('GO', 'Pontalina'),
    ('MG', 'Ponte Nova'),
    ('GO', 'Porangatu'),
    ('MG', 'Porteirinha'),
    ('RS', 'Porto Alegre'),
    ('SC', 'Porto Belo'),
    ('SP', 'Porto Feliz'),
    ('TO', 'Porto Nacional'),
    ('BA', 'Porto Seguro'),
    ('RO', 'Porto Velho'),
    ('MG', 'Pouso Alegre'),
    ('MG', 'Poços de Caldas'),
    ('SP', 'Praia Grande'),
    ('MA', 'Presidente Dutra'),
    ('SP', 'Presidente Epitácio'),
    ('SP', 'Presidente Prudente'),
    ('SP', 'Presidente Venceslau'),
    ('MT', 'Primavera do Leste'),
    ('AL', 'Pão de Açúcar'),
    ('BA', 'Queimadas'),
    ('MT', 'Querência'),
    ('GO', 'Quirinópolis'),
    ('CE', 'Quixadá'),
    ('CE', 'Quixeramobim'),
    ('PR', 'Realeza'),
    ('PE', 'Recife'),
    ('CE', 'Redenção'),
    ('PA', 'Redenção'),
    ('MG', 'Reduto'),
    ('SP', 'Registro'),
    ('BA', 'Remanso'),
    ('RJ', 'Resende'),
    ('RS', 'Restinga Seca'),
    ('BA', 'Riachão do Jacuípe'),
    ('BA', 'Ribeira do Pombal'),
    ('SP', 'Ribeirão Pires'),
    ('SP', 'Ribeirão Preto'),
    ('MG', 'Ribeirão das Neves'),
    ('AC', 'Rio Branco'),
    ('SP', 'Rio Claro'),
    ('RS', 'Rio Grande'),
    ('GO', 'Rio Verde'),
    ('RJ', 'Rio das Ostras'),
    ('RJ', 'Rio de Janeiro'),
    ('SC', 'Rio do Sul'),
    ('RO', 'Rolim de Moura'),
    ('PR', 'Rolândia'),
    ('MT', 'Rondonópolis'),
    ('SP', 'Rosana'),
    ('SP', 'Roseira'),
    ('MG', 'Sabará'),
    ('MG', 'Sabinópolis'),
    ('PE', 'Salgueiro'),
    ('BA', 'Salvador'),
    ('SP', 'Santa Bárbara d´Oeste'),
    ('PE', 'Santa Cruz do Capibaribe'),
    ('SP', 'Santa Cruz do Rio Pardo'),
    ('RS', 'Santa Cruz do Sul'),
    ('SP', 'Santa Fé do Sul'),
    ('MA', 'Santa Inês'),
    ('MG', 'Santa Luzia'),
    ('BA', 'Santa Maria da Vitória'),
    ('ES', 'Santa Maria de Jetibá'),
    ('RS', 'Santa Maria'),
    ('CE', 'Santa Quitéria'),
    ('MG', 'Santa Rita do Sapucaí'),
    ('RS', 'Santa Rosa'),
    ('ES', 'Santa Teresa'),
    ('GO', 'Santa Terezinha de Goiás'),
    ('SP', 'Santana de Parnaíba'),
    ('AL', 'Santana do Ipanema'),
    ('AP', 'Santana'),
    ('PA', 'Santarém'),
    ('SP', 'Santo André'),
    ('PR', 'Santo Antônio da Platina'),
    ('BA', 'Santo Antônio de Jesus'),
    ('RJ', 'Santo Antônio de Pádua'),
    ('RS', 'Santo Ângelo'),
    ('MG', 'Santos Dumont'),
    ('SP', 'Santos'),
    ('RS', 'Sarandi'),
    ('GO', 'Senador Canedo'),
    ('BA', 'Senhor do Bonfim'),
    ('RO', 'Seringueiras'),
    ('RJ', 'Seropédica'),
    ('PE', 'Serra Talhada'),
    ('ES', 'Serra'),
    ('BA', 'Serrinha'),
    ('SP', 'Sertãozinho'),
    ('MG', 'Sete Lagoas'),
    ('MS', 'Sidrolândia'),
    ('BA', 'Simões Filho'),
    ('MT', 'Sinop'),
    ('CE', 'Sobral'),
    ('SP', 'Socorro'),
    ('SP', 'Sorocaba'),
    ('MT', 'Sorriso'),
    ('PB', 'Sousa'),
    ('SP', 'Sumaré'),
    ('PB', 'Sumé'),
    ('PE', 'Surubim'),
    ('SP', 'Suzano'),
    ('SC', 'São Bento do Sul'),
    ('PB', 'São Bento'),
    ('SP', 'São Bernardo do Campo'),
    ('SP', 'São Caetano do Sul'),
    ('SP', 'São Carlos'),
    ('SE', 'São Cristóvão'),
    ('RJ', 'São Fidélis'),
    ('PA', 'São Félix do Xingu'),
    ('ES', 'São Gabriel da Palha'),
    ('RJ', 'São Gonçalo'),
    ('MG', 'São Gotardo'),
    ('SP', 'São Joaquim da Barra'),
    ('PE', 'São José do Egito'),
    ('SP', 'São José do Rio Pardo'),
    ('SP', 'São José do Rio Preto'),
    ('SP', 'São José dos Campos'),
    ('PR', 'São José dos Pinhais'),
    ('MT', 'São José dos Quatro Marcos'),
    ('SC', 'São José'),
    ('MG', 'São João Nepomuceno'),
    ('SP', 'São João da Boa Vista'),
    ('RJ', 'São João de Meriti'),
    ('MG', 'São João del Rei'),
    ('PI', 'São João do Piauí'),
    ('RS', 'São Leopoldo'),
    ('MG', 'São Lourenço'),
    ('GO', 'São Luís de Montes Belos'),
    ('MA', 'São Luís'),
    ('SP', 'São Manuel'),
    ('RS', 'São Marcos'),
    ('MA', 'São Mateus do Maranhão'),
    ('ES', 'São Mateus'),
    ('PR', 'São Miguel do Iguaçu'),
    ('SC', 'São Miguel do Oeste'),
    ('RN', 'São Miguel'),
    ('SP', 'São Paulo'),
    ('PI', 'São Pedro do Piauí'),
    ('PI', 'São Raimundo Nonato'),
    ('SP', 'São Roque'),
    ('MG', 'São Sebastião do Paraíso'),
    ('SP', 'São Sebastião'),
    ('SP', 'São Vicente'),
    ('SP', 'Taboão da Serra'),
    ('SP', 'Taguaí'),
    ('PA', 'Tailândia'),
    ('MT', 'Tangará da Serra'),
    ('RS', 'Tapejara'),
    ('RS', 'Taquara'),
    ('SP', 'Taquaritinga'),
    ('SP', 'Tatuí'),
    ('SP', 'Taubaté'),
    ('AM', 'Tefé'),
    ('BA', 'Teixeira de Freitas'),
    ('PR', 'Telêmaco Borba'),
    ('SP', 'Teodoro Sampaio'),
    ('PI', 'Teresina'),
    ('RJ', 'Teresópolis'),
    ('PR', 'Terra Boa'),
    ('RS', 'Teutônia'),
    ('MG', 'Teófilo Otoni'),
    ('CE', 'Tianguá'),
    ('SP', 'Tietê'),
    ('PE', 'Timbaúba'),
    ('MA', 'Timon'),
    ('MG', 'Timóteo'),
    ('SE', 'Tobias Barreto'),
    ('PR', 'Toledo'),
    ('GO', 'Trindade'),
    ('MG', 'Três Corações'),
    ('MS', 'Três Lagoas'),
    ('MG', 'Três Pontas'),
    ('RJ', 'Três Rios'),
    ('RS', 'Três de Maio'),
    ('SC', 'Tubarão'),
    ('BA', 'Tucano'),
    ('PA', 'Tucumã'),
    ('PA', 'Tucuruí'),
    ('SP', 'Tupi Paulista'),
    ('SP', 'Tupã'),
    ('MG', 'Uberaba'),
    ('MG', 'Uberlândia'),
    ('PR', 'Ubiratã'),
    ('MG', 'Ubá'),
    ('SE', 'Umbaúba'),
    ('PR', 'Umuarama'),
    ('MG', 'Unaí'),
    ('PR', 'União da Vitória'),
    ('GO', 'Uruaçu'),
    ('RS', 'Uruguaiana'),
    ('PI', 'Uruçuí'),
    ('BA', 'Valença'),
    ('RJ', 'Valença'),
    ('SP', 'Valinhos'),
    ('GO', 'Valparaíso de Goiás'),
    ('MG', 'Varginha'),
    ('RJ', 'Vassouras'),
    ('ES', 'Venda Nova do Imigrante'),
    ('MG', 'Vespasiano'),
    ('RS', 'Viamão'),
    ('ES', 'Viana'),
    ('ES', 'Vila Velha'),
    ('RO', 'Vilhena'),
    ('MG', 'Virginópolis'),
    ('MG', 'Visconde do Rio Branco'),
    ('BA', 'Vitória da Conquista'),
    ('PE', 'Vitória de Santo Antão'),
    ('ES', 'Vitória'),
    ('MG', 'Viçosa'),
    ('RJ', 'Volta Redonda'),
    ('SP', 'Votorantim'),
    ('SP', 'Votuporanga'),
    ('MT', 'Várzea Grande'),
    ('PA', 'Xinguara'),
    ('MT', 'Água Boa'),
    ('GO', 'Águas Lindas de Goiás');
