INSERT INTO Categoria_Curso (ger, rotulo)
VALUES
    ('Programas básicos', 'ABI Educação'),
    ('Programas básicos', 'ABI Artes e humanidades'),
    ('Programas básicos', 'ABI Negócios, administração e direito'),
    ('Programas básicos', 'ABI Ciências naturais, matemática e estatística'),
    ('Programas básicos', 'ABI Computação e Tecnologias da Informação e Comunicação (TIC)'),
    ('Programas básicos', 'ABI Engenharia, produção e construção'),
    ('Programas básicos', 'ABI Agricultura, silvicultura, pesca e veterinária'),
    ('Programas básicos', 'ABI Saúde e bem-estar'),
    ('Programas básicos', 'ABI Serviços'),
    ('Educação', 'Ciência da educação'),
    ('Educação', 'Processos escolares'),
    ('Educação', 'Psicopedagogia'),
    ('Educação', 'Educação infantil formação de professor'),
    ('Educação', 'Educação do campo formação de professor'),
    ('Educação', 'Educação especial formação de professor'),
    ('Educação', 'Educação indígena formação de professor'),
    ('Educação', 'Pedagogia'),
    ('Educação', 'Artes formação de professor'),
    ('Educação', 'Artes visuais formação de professor'),
    ('Educação', 'Biologia formação de professor'),
    ('Educação', 'Ciências agrárias formação de professor'),
    ('Educação', 'Ciências naturais formação de professor'),
    ('Educação', 'Ciências sociais formação de professor'),
    ('Educação', 'Cinema e audiovisual formação de professor'),
    ('Educação', 'Computação formação de professor'),
    ('Educação', 'Dança formação de professor'),
    ('Educação', 'Economia doméstica formação de professor'),
    ('Educação', 'Educação do campo em áreas de conhecimento da educação básica formação de professor'),
    ('Educação', 'Educação física formação de professor'),
    ('Educação', 'Educação indígena em áreas de conhecimento da educação básica formação de professor'),
    ('Educação', 'Enfermagem formação de professor'),
    ('Educação', 'Ensino profissionalizante em área específica formação de professor'),
    ('Educação', 'Ensino religioso formação de professor'),
    ('Educação', 'Estatística formação de professor'),
    ('Educação', 'Filosofia formação de professor'),
    ('Educação', 'Física formação de professor'),
    ('Educação', 'Geografia formação de professor'),
    ('Educação', 'História formação de professor'),
    ('Educação', 'Matemática formação de professor'),
    ('Educação', 'Música formação de professor'),
    ('Educação', 'Psicologia formação de professor'),
    ('Educação', 'Química formação de professor'),
    ('Educação', 'Teatro formação de professor'),
    ('Educação', 'Letras alemão formação de professor'),
    ('Educação', 'Letras espanhol formação de professor'),
    ('Educação', 'Letras francês formação de professor'),
    ('Educação', 'Letras inglês formação de professor'),
    ('Educação', 'Letras italiano formação de professor'),
    ('Educação', 'Letras japonês formação de professor'),
    ('Educação', 'Letras língua brasileira de sinais formação de professor'),
    ('Educação', 'Letras línguas estrangeiras clássicas formação de professor'),
    ('Educação', 'Letras linguística formação de professor'),
    ('Educação', 'Letras outras línguas estrangeiras modernas formação de professor'),
    ('Educação', 'Letras português alemão formação de professor'),
    ('Educação', 'Letras português espanhol formação de professor'),
    ('Educação', 'Letras português formação de professor'),
    ('Educação', 'Letras português francês formação de professor'),
    ('Educação', 'Letras português inglês formação de professor'),
    ('Educação', 'Letras português italiano formação de professor'),
    ('Educação', 'Letras português japonês formação de professor'),
    ('Educação', 'Letras português língua brasileira de sinais formação de professor'),
    ('Educação', 'Letras português línguas estrangeiras clássicas formação de professor'),
    ('Educação', 'Letras português outras línguas estrangeiras modernas formação de professor'),
    ('Educação', 'Letras tradutor e intérprete formação de professor'),
    ('Educação', 'Programas interdisciplinares abrangendo educação'),
    ('Artes e humanidades', 'Animação'),
    ('Artes e humanidades', 'Cinema e audiovisual'),
    ('Artes e humanidades', 'Comunicação assistiva'),
    ('Artes e humanidades', 'Design gráfico'),
    ('Artes e humanidades', 'Fotografia'),
    ('Artes e humanidades', 'Produção audiovisual'),
    ('Artes e humanidades', 'Produção cênica'),
    ('Artes e humanidades', 'Produção cultural'),
    ('Artes e humanidades', 'Produção fonográfica'),
    ('Artes e humanidades', 'Produção multimídia'),
    ('Artes e humanidades', 'Desenho industrial'),
    ('Artes e humanidades', 'Design'),
    ('Artes e humanidades', 'Design de interiores'),
    ('Artes e humanidades', 'Design de produto'),
    ('Artes e humanidades', 'Moda'),
    ('Artes e humanidades', 'Artes'),
    ('Artes e humanidades', 'Artes plásticas'),
    ('Artes e humanidades', 'Artes visuais'),
    ('Artes e humanidades', 'História da arte'),
    ('Artes e humanidades', 'Fabricação de instrumentos musicais não industrial'),
    ('Artes e humanidades', 'Artes cênicas'),
    ('Artes e humanidades', 'Dança'),
    ('Artes e humanidades', 'Música'),
    ('Artes e humanidades', 'Teatro'),
    ('Artes e humanidades', 'Ciências da religião'),
    ('Artes e humanidades', 'Teologia'),
    ('Artes e humanidades', 'Arqueologia'),
    ('Artes e humanidades', 'Conservação e restauro'),
    ('Artes e humanidades', 'História'),
    ('Artes e humanidades', 'Filosofia'),
    ('Artes e humanidades', 'Letras alemão'),
    ('Artes e humanidades', 'Letras escrita criativa'),
    ('Artes e humanidades', 'Letras espanhol'),
    ('Artes e humanidades', 'Letras francês'),
    ('Artes e humanidades', 'Letras inglês'),
    ('Artes e humanidades', 'Letras italiano'),
    ('Artes e humanidades', 'Letras japonês'),
    ('Artes e humanidades', 'Letras língua brasileira de sinais'),
    ('Artes e humanidades', 'Letras línguas estrangeiras clássicas'),
    ('Artes e humanidades', 'Letras linguística'),
    ('Artes e humanidades', 'Letras outras línguas estrangeiras modernas'),
    ('Artes e humanidades', 'Letras português'),
    ('Artes e humanidades', 'Letras português alemão'),
    ('Artes e humanidades', 'Letras português espanhol'),
    ('Artes e humanidades', 'Letras português francês'),
    ('Artes e humanidades', 'Letras português inglês'),
    ('Artes e humanidades', 'Letras português italiano'),
    ('Artes e humanidades', 'Letras português japonês'),
    ('Artes e humanidades', 'Letras português língua brasileira de sinais'),
    ('Artes e humanidades', 'Letras português línguas estrangeiras clássicas'),
    ('Artes e humanidades', 'Letras português outras línguas estrangeiras modernas'),
    ('Artes e humanidades', 'Letras tradutor e intérprete'),
    ('Artes e humanidades', 'Programas interdisciplinares abrangendo artes e humanidades'),
    ('Ciências sociais, comunicação e informação', 'Economia'),
    ('Ciências sociais, comunicação e informação', 'Antropologia'),
    ('Ciências sociais, comunicação e informação', 'Ciência política'),
    ('Ciências sociais, comunicação e informação', 'Ciências sociais'),
    ('Ciências sociais, comunicação e informação', 'Geografia'),
    ('Ciências sociais, comunicação e informação', 'Relações internacionais'),
    ('Ciências sociais, comunicação e informação', 'Sociologia'),
    ('Ciências sociais, comunicação e informação', 'Psicologia'),
    ('Ciências sociais, comunicação e informação', 'Comunicação social'),
    ('Ciências sociais, comunicação e informação', 'Jornalismo'),
    ('Ciências sociais, comunicação e informação', 'Produção editorial'),
    ('Ciências sociais, comunicação e informação', 'Rádio, TV e internet'),
    ('Ciências sociais, comunicação e informação', 'Arquivologia'),
    ('Ciências sociais, comunicação e informação', 'Biblioteconomia'),
    ('Ciências sociais, comunicação e informação', 'Gestão da informação'),
    ('Ciências sociais, comunicação e informação', 'Museologia'),
    ('Ciências sociais, comunicação e informação', 'Programas interdisciplinares abrangendo ciências sociais, comunicação e informação');
